In [1]:
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# df = pd.read_csv("./results/sb3_eval_results.csv")
df = pd.read_csv("./results/fair_gnn_eval_results.csv")
# df = pd.read_csv("./results/greedy_gnn_eval_results.csv")
df

     corpus_size  run  episode  sum_reward
0              5  NaN        1       0.000
1              5  NaN        2      -0.106
2              5  NaN        3      -0.368
3              5  NaN        4      -0.588
4              5  NaN        5       0.000
..           ...  ...      ...         ...
507           40  NaN      124      -1.560
508           40  NaN      125      -0.584
509           40  NaN      126      -3.228
510           40  NaN      127      -0.758
511           40  NaN      128      -1.778

[512 rows x 4 columns]

In [3]:
avg_episode_total_rewards = (
    df.groupby(["corpus_size"])["sum_reward"]
    .mean()
    .reset_index()
    .rename(columns={"sum_reward": "average total reward"})
)
avg_episode_total_rewards

   corpus_size  average total reward
0            5             -0.256047
1           10             -0.162578
2           20             -1.009031
3           40             -1.388063